Repository meshery/meshery-traefik-mesh, pull requests merged in 2021-09, with the labels that each got.

#111 Use MeshKit's config provider for threadsafe operations
  internal/config/config.go
  main.go
  traefik/traefik.go
Labels: language/go

#116 [build] nodejs compatible base container img
  .github/workflows/build-and-release.yml
  .github/workflows/ci.yml
  Dockerfile
Labels: area/ci

#115 added runtime component generation
  main.go
  traefik/error.go
Labels: component/patterns

#124 fixed panic
  main.go
Labels: component/patterns
