Repository meshery/meshery-traefik-mesh, pull requests merged in 2022-10, with the labels that each got.

#222 Upgrade Go 1.19
  .github/workflows/build-and-release.yml
  .github/workflows/ci.yml
  .github/workflows/e2etest.yaml
  .github/workflows/error-ref-publisher.yaml
  .github/workflows/label-commenter.yml
  .github/workflows/update_components.yaml
  .golangci.yml
  Dockerfile
  Makefile
  build/Makefile.core.mk
  build/config.go
  go.mod
  go.sum
  internal/config/releases.go
  main.go
  traefik/error.go
  traefik/sample-apps.go
  traefik/traefik.go
Labels: kind/chore, language/go

#234 Added components to doc workflow
  .github/workflows/components-to-doc.yml
Labels: area/ci, area/docs, area/tests

#231 [CI] fix the first PR merge comment broken image link
  .github/config.yml
Labels: kind/bug, hacktoberfest, area/ci

#235 [chore] Upgrade meshkit and meshery-adapter-library
  go.mod
  go.sum
Labels: kind/chore, language/go

#226 [Readme] Consistently present Meshery logo
  README.md
  img/readme/meshery-logo-dark-text-side.svg
  img/readme/meshery-logo-light-text-side.svg
Labels: hacktoberfest, area/docs
